[theme]
name = "one_light_material"
appearance = "light"

[colors]
background = { scale = "gray", index = 0 }
foreground = { scale = "gray", index = 10 }
primary = { scale = "blue", index = 5 }
secondary = { scale = "green", index = 5 }
error = { scale = "red", index = 5 }
warning = { scale = "yellow", index = 5 }

[overrides]
"Button.background" = { scale = "blue", index = 5 }
"Button.foreground" = { scale = "gray", index = 0 }
"Button.hover_background" = { scale = "blue", index = 7 }
"Button.hover_foreground" = { scale = "gray", index = 0 }
"Button.active_background" = { scale = "blue", index = 9 }
"Button.active_foreground" = { scale = "gray", index = 0 }
