name = "One Dark"
appearance = "dark"

[colors]
background = { h = 0.0, s = 0.0, l = 0.15, a = 1.0 }
foreground = { h = 0.0, s = 0.0, l = 0.7, a = 1.0 }
primary = { h = 0.61, s = 0.35, l = 0.6, a = 1.0 }
secondary = { h = 0.1, s = 0.5, l = 0.5, a = 1.0 }
accent = { h = 0.0, s = 0.5, l = 0.5, a = 1.0 }

[ui_elements]
button = "primary"
text = "foreground"
background = "background"
highlight = "accent"
border = "secondary"
