```toml
[theme]
name = "one_darker"
appearance = "dark"

[colors]
background = { scale = "gray", index = 11 }
foreground = { scale = "gray", index = 1 }
primary = { scale = "blue", index = 9 }
secondary = { scale = "green", index = 7 }
error = { scale = "red", index = 9 }
warning = { scale = "yellow", index = 9 }
info = { scale = "blue", index = 7 }
success = { scale = "green", index = 9 }
```